name: Release Statically Linked Rust Binary

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl       # Linux (musl)
          - aarch64-unknown-linux-musl      # ARM Linux (musl)

    env:
      BINARY_NAME: todo_task

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust (Nightly)
        uses: dtolnay/rust-toolchain@nightly

      - name: Install Cross
        run: cargo install cross

      - name: Build with Cross
        run: cross build --target ${{ matrix.target }} --release

      - name: Create Release Archive
        run: |
          mkdir -p release

          if [[ "${{ matrix.target }}" == *"windows"* ]]; then
            cp target/${{ matrix.target }}/release/$BINARY_NAME.exe release/
            zip -r release/${{ matrix.target }}.zip release/*
          elif [[ "${{ matrix.target }}" == *"darwin"* ]]; then
            cp target/${{ matrix.target }}/release/$BINARY_NAME release/
            tar -czvf release/${{ matrix.target }}.tar.gz -C release $BINARY_NAME
          else
            cp target/${{ matrix.target }}/release/$BINARY_NAME release/
            tar -czvf release/${{ matrix.target }}.tar.gz -C release $BINARY_NAME
          fi

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/*.tar.gz
            release/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.TODO_TOKEN }}
